### ISSUE TITLE
Please update rus

### ISSUE THREAD

**Issue by osiriso1** [pastuh/hllminicalculator#2]
Привет, добавь распознавание русского языка.

**Comment by pastuh** [comment]
You can switch to any language after activating voice commands (click bottom right text: "Activate voice"). 
To switch to Russian, simply say one of the following word in English: "Russian," "Russia," "Ruski" 
Afterward, you can then speak any number in the Russian language.

The supported voice commands are as follows:
Russian
Japanese
Dutch
Indonesian
Polish
Cantonese
Mandarin
Portuguese
Italian
Spanish
German
Hindi
